# Generated by Django 3.1.2 on 2020-11-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credits',
            old_name='user',
            new_name='username',
        ),
    ]
