# Generated by Django 3.1.2 on 2020-11-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_auto_20201129_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credits',
            old_name='username',
            new_name='user',
        ),
    ]
