# Generated by Django 3.1.2 on 2020-11-30 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0005_auto_20201130_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_reports',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
