# Generated by Django 3.1.2 on 2020-11-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0006_message_reports_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_reports',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
