# Generated by Django 3.1.2 on 2020-11-30 05:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0007_auto_20201130_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_reports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 5, 19, 54, 203328, tzinfo=utc)),
        ),
    ]
