# Generated by Django 3.1.2 on 2020-11-30 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0008_auto_20201130_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_reports',
            name='request_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message_reports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 5, 25, 27, 288538, tzinfo=utc)),
        ),
    ]
