# Generated by Django 3.1.2 on 2020-11-30 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0011_auto_20201130_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_reports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 18, 51, 41, 105387, tzinfo=utc)),
        ),
    ]
