# Generated by Django 3.1.2 on 2020-12-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0013_auto_20201201_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_reports',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
