# Generated by Django 3.1.2 on 2020-12-01 08:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0017_auto_20201201_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_reports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 8, 3, 47, 203052, tzinfo=utc)),
        ),
    ]
