# Generated by Django 3.1.2 on 2020-12-01 08:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0018_auto_20201201_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_reports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 8, 28, 11, 808791, tzinfo=utc)),
        ),
    ]
